language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install MySQL-python
  - pip install coverage
script: ./runtests 
before_script:
  - mysql -e 'create database hostinfo'
  - python hostinfo/manage.py syncdb --noinput
services:
  - mysql
