language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install psycopg2
  - pip install coverage
addons:
  Postgresql: "9.3"
before_script:
  - psql -c 'create database hostinfo;' -U postgres
  - python hostinfo/manage.py syncdb --noinput
script: ./runtests 
